# Generated by Django 2.0.13 on 2019-03-11 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20190310_2019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='captions',
            new_name='caption',
        ),
    ]
